### ISSUE TITLE
Carregamento de array caso ele não seja um array

### ISSUE THREAD

**Issue by tiagolopesdev** [tiagolopesdev/scage-frontend#3]
Estou com o seguinte problema:

* Mudei para uma função da seguinte forma (arquivo `src\Utils\manageFeedbackDisplay.tsx`):
```javascript
import { Alert, Skeleton } from "@mui/material"
import { CustomMessageError } from "../Components/CustomMessageError"

export enum Element {
  SCALE = "Escalas",
  COLLABORATORS = "Colaboradores",
  STATISTICS = "Estatisticas"
}

export function manageFeedbackDisplay(
  conditionDisplaySkeleton: boolean,
  conditionDisplayElement: boolean,
  conditionFilter: string,
  typeElement: Element,
  elements: JSX.Element
) {
  if (conditionDisplaySkeleton) {
    return <Skeleton variant="rounded" width="100%" height='50rem' />
  } 
  else if (conditionDisplayElement) {
    return elements
  }
  return conditionFilter === '' ?
    <CustomMessageError message={`${typeElement} não foram possíveis serem exibidas`} /> :
    <Alert severity="info">{`${typeElement}, {conditionFilter} não encontrada!`}</Alert>
}
```

Ao tentar utilizá-la, usando o código abaixo (arquivo `src\Components\Scales\scale-list-floating.tsx`), estou tendo o seguinte erro:
```javascript
useEffect(() => {
    managementFindScales()
  }, [selectedMonth, scaleContext])

  const managerScaleRender = manageFeedbackDisplay(
    scales.length === 0,
    !isLoading && scales.length > 0,
    selectedMonth,
    Element.SCALE,
    <div id="group-scales-single">
      {scales.map((scale) => {
        return <div key={scale.id}>
          <Scale scale={scale} />
        </div>
      })}
    </div>
  )

  return <ContainerScaleList>
    <ContainerComboBoxStyle>
      <Input
        value={selectedMonth}
        label='Digite o nome do mês'
        onChange={(event: any) => {
          setSelectedMonth(event.target.value ?? '')
        }}
      />
    </ContainerComboBoxStyle>
    <ScroolCustom style={!isLoading && (scales.length === 0 || scales.length === undefined) ? {
      display: 'flex', alignItems: 'center',
      alignContent: 'center',
      justifyContent: 'center'
    } : undefined} >
      {managerScaleRender}
    </ScroolCustom>
  </ContainerScaleList>
`````

Erro: 

![image](https://github.com/tiagolopesdev/scage-frontend/assets/58925056/e80502d0-541a-4717-972d-9977b3900524)

Entendo que com o código anterior que eu estava utilizando, pelo fato de ter a condição, ele não carregava o conteúdo e isso evitava o erro. Contudo, quero implementar esse código para centralizar a lógica e deixar reutilizavel para as outras partes do sistema a qual há necessidade.

**Comment by vhs0s0** [comment]
## src\Utils\manageFeedbackDisplay.tsx

No primeiro código que é onde você criou a função reutilizável, eu acho que seria melhor você mudar o tipo de `JSX.Element` para  `React.ReactNode` uma vez que  ReactNode é um tipo do React que permite inferir qualquer tipo de element seja ele tags html, strings, números etc...

Além disso ao invés de aceitar as propriedades por parâmetro assim, ao meu ver, é melhor passar um objeto aonde cada opção tem sua chave. Exemplo:

```tsx
import { Alert, Skeleton } from "@mui/material"
import { CustomMessageError } from "../Components/CustomMessageError"
import { ReactNode } from "react";

export enum Element {
  SCALE = "Escalas",
  COLLABORATORS = "Colaboradores",
  STATISTICS = "Estatisticas"
}

interface ManageFeedbackDisplayProps {
  elements: ReactNode;
  typeElement: Element;
  filter?: string;
  showSkeleton?: boolean;
  showElement?: boolean;
}

export function manageFeedbackDisplay({
   elements,
   typeElement,
   filter,
   showSkeleton = false,
   showElement = true,
}: ManageFeedbackDisplayProps) 
{
  if (showSkeleton) {
    return <Skeleton variant="rounded" width="100%" height='50rem' />
  } 
  else if (showElement) {
    return elements
  }
  return filter ?
    <CustomMessageError message={`${typeElement} não foram possíveis serem exibidas`} /> :
    <Alert severity="info">{`${typeElement}, {filter} não encontrada!`}</Alert>
}

```

Dessa forma garantimos que o desenvolvedor sempre saberá o que passar para a função manageFeedbackDisplay sem depender do intelissense do javascript pra dizer quais argumentos a função espera. Além disso não há necessidade de se preocupar com a ordem dos parâmetros passados, uma vez que é um objeto e tanto faz a ordem das chaves/valores.

Uma última coisa em relação a essa função é que agora ela tem propriedades opcionais que faz com que nao precise ser passadas, e caso não sejam passadas, ele atribui valores padrão para elas, como no exemplo acima, eu passei para o showElement e showSkeleton, mas edite como preferir.

Lembrando que tudo acima é melhoria, não impacta no erro que você passou. Vou falar do erro agora!

## src\Components\Scales\scale-list-floating.tsx

No segundo arquivo o que temos de erro aqui é você estar fazendo essa parte do código:

```tsx
// ....
 <div id="group-scales-single">
      {scales.map((scale) => { // o Erro possívelmente está nessa linha
        return <div key={scale.id}>
          <Scale scale={scale} />
        </div>
      })}
    </div>
// ...
```
`scales.map` muitas das vezes vai dar o erro de  "Is not a function" por que na 1° renderização scales não é uma array.

Caso esse scales seja um estado você pode atribuir como valor inicial uma *array vazia* Algo como:

```tsx
const [scales, setScales] = useState</*O Tipo do Scales aqui*/ any>([]) // coloquei `[]` como valor inicial
```

Assim essa variavel sempre será uma array e nao vai dar o erro de scales.map.

Caso ainda ocorra substitua o código mencionado acima por esse:

```tsx
// ....
 <div id="group-scales-single">
      {[].concat(scales ?? [])?.map((scale) => {
        return <div key={scale.id}>
          <Scale scale={scale} />
        </div>
      })}
    </div>
// ...
```

```tsx
[].concat(scales ?? [])? // Essa parte
```

Pode parecer gambiarra, e até é, mas isso garante que sempre será uma array a qual vai estar recebendo um `.map()`. Uma opção mais simples do que isso, mas que ainda pode nao funcionar é simplesmente por um `?` na frente do `scales`, algo como:

```tsx
// ....
 <div id="group-scales-single">
      {scales?.map((scale) => { // Coloquei o  ? na frente da variavel scales
        return <div key={scale.id}>
          <Scale scale={scale} />
        </div>
      })}
    </div>
// ...
```

Caso nada disso funciona, veja o que a sua API está retornando, e se você está atribuindo uma lista para essa variavel. O erro que está ocorrendo hoje é devido ele olhar para scales e nao se deparar com uma array, logo .map nao funciona.

**Comment by tiagolopesdev** [comment]
Deu certo man, só precisei fazer uma correção pra usar a implementação que você indicou. O código ficou  assim: 
```javascript
{([] as ISingleScale[]).concat(scales ?? [])?.map((scale) => {
        return <div key={scale.id}>
          <Scale scale={scale} />
        </div>
})}
`````
Foi preciso fazer, de certa forma foi preciso tipar o array:
````javascript
([] as ISingleScale[]).concat()
````

**Comment by vhs0s0** [comment]
Top Man, que bom que deu certo
